const $=s=>document.querySelector(s);const app=$('#app');
const state=JSON.parse(localStorage.getItem('histodaily.v01')||'{"xp":0,"done":[],"streak":0,"last":""}');
function save(){localStorage.setItem('histodaily.v01',JSON.stringify(state))}
function today(){return new Date().toISOString().slice(0,10)}
function markDone(id,xp){if(!state.done.includes(id)){state.done.push(id);state.xp+=xp;state.streak=state.last===today()?state.streak:state.streak+1;state.last=today();save()}}
let route='home', current=null, screen=0, quiz=0, score=0, answered=false;
function shell(content){app.innerHTML=`<main class="wrap"><div class="top"><div class="brand">HistoDaily</div><div class="pill">${state.xp} XP · 🔥 ${state.streak}</div></div>${content}</main><nav class="nav"><button class="${route==='home'?'active':''}" onclick="go('home')">Accueil</button><button class="${route==='path'?'active':''}" onclick="go('path')">Parcours</button><button class="${route==='review'?'active':''}" onclick="go('review')">Réviser</button><button class="${route==='profile'?'active':''}" onclick="go('profile')">Profil</button></nav>`}
function go(r){route=r;render()}
function render(){ if(route==='home')home(); if(route==='path')path(); if(route==='review')review(); if(route==='profile')profile(); if(route==='lesson')lesson(); if(route==='quiz')quizView();}
function home(){let done=state.done.length,total=LESSONS.length; shell(`<section class="card hero"><span class="kicker">V0.1 · Préhistoire</span><h1>5 à 10 minutes d’histoire</h1><p>Cette version sert à valider le vrai format : plus de texte, plusieurs écrans par leçon, puis 8 questions.</p><div class="progress"><div class="bar" style="width:${done/total*100}%"></div></div><p class="muted small">${done}/${total} leçons terminées</p><button class="btn" onclick="startNext()">Continuer</button><button class="btn secondary" onclick="go('path')">Voir le parcours</button></section><section class="card"><h2>Règle du jeu</h2><p>Lis les écrans dans l’ordre. Le quiz n’apparaît qu’à la fin. Si tu réussis, tu gagnes l’XP de la leçon.</p></section>`) }
function startNext(){let l=LESSONS.find(x=>!state.done.includes(x.id))||LESSONS[0];startLesson(l.id)}
function path(){shell(`<section class="card"><span class="kicker">Parcours</span><h1>Préhistoire</h1><p>On commence volontairement petit : deux leçons longues pour tester le style avant d’en écrire dix.</p></section><div class="grid">${LESSONS.map((l,i)=>`<section class="card lesson"><div><div class="kicker">Leçon ${i+1}</div><h2>${l.title}</h2><p class="muted">${l.screens.length} écrans · ${l.quiz.length} questions · ${l.xp} XP</p></div><div><div class="badge">${state.done.includes(l.id)?'✓ fini':'à faire'}</div><button class="btn secondary" onclick="startLesson('${l.id}')">Ouvrir</button></div></section>`).join('')}</div>`) }
function startLesson(id){current=LESSONS.find(l=>l.id===id);screen=0;route='lesson';render()}
function lesson(){let s=current.screens[screen];shell(`<section class="card"><span class="kicker">${current.era} · écran ${screen+1}/${current.screens.length}</span><h1>${s.title}</h1><div class="screenText">${s.text}</div><div class="progress"><div class="bar" style="width:${(screen+1)/current.screens.length*100}%"></div></div><button class="btn" onclick="nextScreen()">${screen===current.screens.length-1?'Passer au quiz':'Continuer'}</button><button class="btn ghost" onclick="go('path')">Quitter</button></section>`) }
function nextScreen(){if(screen<current.screens.length-1){screen++;render()}else{quiz=0;score=0;answered=false;route='quiz';render()}}
function quizView(){let q=current.quiz[quiz];let pct=(quiz/current.quiz.length)*100;shell(`<section class="card"><span class="kicker">Quiz · question ${quiz+1}/${current.quiz.length}</span><h1>${q.q}</h1><div class="progress"><div class="bar" style="width:${pct}%"></div></div><div>${q.a.map((a,i)=>`<button class="choice" onclick="answer(${i})">${a}</button>`).join('')}</div><p id="feedback" class="muted"></p><button id="nextBtn" class="btn" style="display:none" onclick="nextQ()">Continuer</button></section>`) }
function answer(i){if(answered)return;answered=true;let q=current.quiz[quiz];document.querySelectorAll('.choice').forEach((b,idx)=>{if(idx===q.ok)b.classList.add('correct'); if(idx===i&&idx!==q.ok)b.classList.add('wrong')}); if(i===q.ok){score++;$('#feedback').textContent='Bonne réponse.'}else{$('#feedback').textContent='Pas grave, cette notion reviendra en révision.'}$('#nextBtn').style.display='block'}
function nextQ(){answered=false;if(quiz<current.quiz.length-1){quiz++;render()}else{markDone(current.id,current.xp);shell(`<section class="card hero"><span class="kicker">Leçon terminée</span><h1>${score}/${current.quiz.length}</h1><p>Tu as gagné ${current.xp} XP. Même si tu t’es trompé, l’important est de revoir les notions régulièrement.</p><button class="btn" onclick="go('path')">Retour au parcours</button><button class="btn secondary" onclick="startNext()">Leçon suivante</button></section>`)}}
function review(){let done=LESSONS.filter(l=>state.done.includes(l.id));shell(`<section class="card"><span class="kicker">Révision</span><h1>Revoir les notions</h1><p>Pour l’instant, la révision reprend les leçons terminées. Plus tard, elle ciblera précisément les erreurs.</p>${done.length?done.map(l=>`<button class="btn secondary" onclick="startLesson('${l.id}')">Relire : ${l.title}</button>`).join(''):'<p class="muted">Termine une leçon pour débloquer la révision.</p>'}</section>`) }
function profile(){shell(`<section class="card"><span class="kicker">Profil</span><h1>Ton apprentissage</h1><div class="stat"><span>XP total</span><b>${state.xp}</b></div><div class="stat"><span>Série</span><b>${state.streak} jour(s)</b></div><div class="stat"><span>Leçons terminées</span><b>${state.done.length}/${LESSONS.length}</b></div><button class="btn ghost" onclick="resetAll()">Réinitialiser</button></section>`) }
function resetAll(){if(confirm('Réinitialiser la progression ?')){localStorage.removeItem('histodaily.v01');location.reload()}}
render();
