const lessons=[
{ id:'neo', era:'Préhistoire', icon:'🌾', title:'Le Néolithique : le jour où l’humain s’installe', minutes:8, xp:30,
pages:[
{t:'Avant les villes : des humains en mouvement',body:`Pendant l’immense majorité de son histoire, l’être humain ne vit pas dans des villages fixes. Il se déplace. Il suit les troupeaux, les saisons, les zones où l’on trouve des fruits, des racines, du poisson ou du gibier. Ce monde n’est pas “primitif” au sens idiot du mot : les chasseurs-cueilleurs connaissent très bien leur environnement, fabriquent des outils, transmettent des savoirs, racontent probablement des histoires, décorent des objets et parfois des grottes.\n\nMais leur façon de vivre impose une limite : on ne peut pas accumuler beaucoup de choses quand on doit bouger souvent. Pas question de posséder une énorme maison, un grenier plein ou des champs qui demandent des mois de soin. La richesse existe, mais elle ne prend pas encore la forme de terres, de stocks ou de bâtiments.\n\nLe Néolithique change ça. Petit à petit, dans plusieurs régions du monde, des groupes humains comprennent qu’ils peuvent influencer la nature au lieu de seulement la suivre. Ils sélectionnent des graines, protègent certaines plantes, gardent des animaux près d’eux. Ils ne “découvrent” pas l’agriculture en une seule journée : c’est une longue série d’essais, d’habitudes et d’adaptations.`},
{t:'Pourquoi l’agriculture change tout',body:`Cultiver une céréale paraît banal aujourd’hui. Pourtant, c’est une révolution mentale. Une graine plantée maintenant donnera quelque chose plus tard. Il faut donc rester près d’un territoire, prévoir, attendre, protéger, stocker. L’humain entre dans un rapport plus durable avec le lieu.\n\nAvec les récoltes vient le stockage. Avec le stockage vient la possibilité de nourrir plus de monde, mais aussi de défendre ce que l’on possède. Un village peut grandir. Certains individus peuvent se spécialiser : fabriquer de meilleurs outils, construire, organiser les réserves, surveiller les troupeaux. L’agriculture permet donc plus de population, plus d’organisation, mais aussi plus de conflits et plus d’inégalités.\n\nCe n’est pas simplement “le progrès”. Les premiers agriculteurs travaillent souvent plus dur que les chasseurs-cueilleurs. Leur alimentation peut devenir moins variée. Les maladies se diffusent plus facilement quand les humains vivent serrés avec des animaux. Mais la dynamique est lancée : villages, champs, greniers, hiérarchies, échanges, puis plus tard villes et États.`},
{t:'Des foyers multiples, pas une invention unique',body:`On parle souvent du Croissant fertile, au Proche-Orient, parce que c’est une région très importante pour l’apparition de l’agriculture : blé, orge, chèvres, moutons. Mais il ne faut pas imaginer un seul inventeur génial qui aurait tout lancé. L’agriculture apparaît à plusieurs endroits du monde, à des périodes différentes : en Chine avec le riz et le millet, en Amérique avec le maïs, dans les Andes avec la pomme de terre, en Afrique avec certaines céréales locales.\n\nCela veut dire que le Néolithique n’est pas un événement unique daté comme une bataille. C’est une transformation mondiale, lente, irrégulière. Certaines sociétés l’adoptent, d’autres non, parfois parce que leur mode de vie fonctionne très bien autrement.\n\nÀ retenir : le Néolithique, ce n’est pas seulement “des outils en pierre polie”. C’est le passage progressif vers la production de nourriture, la sédentarisation, le stockage et des sociétés plus complexes.`}
],
quiz:[['Quel changement définit le mieux le Néolithique ?',['L’apparition des dinosaures','La production de nourriture par agriculture et élevage','La découverte de l’électricité','La chute de Rome'],1],['Pourquoi le stockage est-il important ?',['Il permet de rester plus longtemps au même endroit','Il supprime toutes les maladies','Il empêche les conflits','Il rend tout le monde égal'],0],['Le Néolithique apparaît-il en un seul lieu ?',['Oui, uniquement en Égypte','Oui, uniquement à Rome','Non, plusieurs régions connaissent des transformations proches','Non, mais uniquement en Europe'],2],['Quel effet négatif possible accompagne la sédentarisation ?',['Moins de contacts avec les animaux','Plus de diffusion des maladies','Disparition immédiate des villages','Fin de toute hiérarchie'],1],['Pourquoi l’agriculture demande-t-elle de prévoir ?',['Parce qu’une récolte arrive plus tard','Parce qu’elle ne dépend jamais des saisons','Parce qu’elle est instantanée','Parce qu’elle se fait uniquement en ville'],0],['Le Croissant fertile est surtout associé à…',['blé, orge, chèvres et moutons','maïs et pomme de terre','riz uniquement','cacao uniquement'],0],['Le Néolithique est plutôt…',['une transformation lente','une bataille','un empire','une religion'],0],['Quel élément favorise les inégalités ?',['L’absence totale de biens','Les stocks et les terres à contrôler','Le fait de marcher beaucoup','La disparition des villages'],1]]},
{ id:'egypte', era:'Antiquité', icon:'🏺', title:'L’Égypte : le pouvoir né du Nil', minutes:9, xp:35,
pages:[
{t:'Un pays construit par un fleuve',body:`L’Égypte ancienne est presque incompréhensible si l’on oublie le Nil. Le pays est un long ruban fertile entouré de zones désertiques. Chaque année, les crues déposent du limon, une terre riche qui permet de cultiver. Le Nil sert aussi d’autoroute : on transporte des marchandises, des pierres, des hommes, des ordres et des impôts.\n\nCette géographie crée une situation particulière. Là où d’autres régions doivent composer avec des frontières ouvertes, l’Égypte est relativement protégée par les déserts et la mer. Le pouvoir peut donc se concentrer autour du contrôle du fleuve, des terres et des récoltes. Celui qui organise l’irrigation, les greniers et les travaux collectifs possède un avantage énorme.\n\nL’État égyptien naît de cette capacité à organiser. Il faut mesurer les champs après les crues, prélever des ressources, mobiliser des travailleurs, entretenir les temples, gérer les scribes. L’Égypte n’est pas seulement un pays de pyramides : c’est une machine administrative impressionnante.`},
{t:'Pharaon : roi, dieu et symbole d’ordre',body:`Le pharaon n’est pas un roi ordinaire. Il incarne l’ordre du monde, ce que les Égyptiens appellent la Maât : équilibre, justice, stabilité cosmique. Sa fonction n’est pas seulement politique, elle est religieuse. Gouverner, rendre la justice, construire des temples, assurer les rites : tout cela participe au maintien de l’ordre contre le chaos.\n\nCette vision explique pourquoi les monuments sont si importants. Une pyramide ou un temple n’est pas seulement une démonstration de richesse. C’est un message : le pays est organisé, le souverain est puissant, l’ordre est maintenu, les dieux sont honorés.\n\nBien sûr, derrière cette image sacrée, il y a des réalités très concrètes : impôts, corvées, carrières de pierre, artisans spécialisés, scribes capables de lire et d’écrire. L’écriture hiéroglyphique n’est pas seulement décorative ; elle sert aussi à administrer, compter, commémorer et légitimer le pouvoir.`},
{t:'Pourquoi l’Égypte fascine encore',body:`L’Égypte impressionne parce qu’elle combine durée, puissance visuelle et mystère apparent. Les pyramides sont déjà anciennes quand de nombreuses civilisations méditerranéennes se développent. Pour un Romain, l’Égypte est elle-même une antiquité. Cette profondeur donne le vertige.\n\nMais il faut éviter l’image d’une Égypte figée pendant trois mille ans. Elle connaît des périodes d’unité, de crise, d’invasions, de réformes, de conquêtes. Les pharaons ne sont pas tous les mêmes, les capitales changent, les influences extérieures existent.\n\nÀ retenir : l’Égypte ancienne est une civilisation du fleuve, de l’administration et du sacré. Sa force vient autant de ses champs et de ses scribes que de ses monuments.`}
],
quiz:[['Quel élément structure le plus l’Égypte ancienne ?',['Le Nil','Les Alpes','La forêt amazonienne','La Manche'],0],['Que dépose la crue du Nil ?',['Du limon fertile','Du pétrole','Du charbon','Du sel uniquement'],0],['La Maât désigne surtout…',['l’ordre et l’équilibre','une arme','une ville grecque','un impôt romain'],0],['Le pharaon est seulement un chef militaire ?',['Oui','Non, il a aussi une dimension religieuse et symbolique'],1],['À quoi servent aussi les hiéroglyphes ?',['Administrer et commémorer','Uniquement décorer les murs','Remplacer les bateaux','Faire de la monnaie'],0],['Pourquoi le Nil facilite-t-il l’État ?',['Il permet transport, agriculture et contrôle des récoltes','Il empêche toute organisation','Il rend l’écriture inutile','Il sépare toutes les villes'],0],['Les pyramides sont seulement des tas de pierres ?',['Oui','Non, elles portent un message politique et religieux'],1],['L’Égypte ancienne est-elle totalement immobile pendant 3000 ans ?',['Oui','Non, elle connaît crises, changements et influences'],1]]},
{ id:'rome', era:'Antiquité', icon:'🦅', title:'Rome : de petite cité à empire méditerranéen', minutes:10, xp:40,
pages:[
{t:'Rome commence petit',body:`Quand on pense à Rome, on imagine souvent l’Empire, les légions, les routes, les arènes et les empereurs. Pourtant, Rome commence comme une cité parmi d’autres en Italie. Son histoire est justement fascinante parce qu’elle montre comment une communauté locale devient progressivement une puissance régionale, puis méditerranéenne.\n\nLa force de Rome ne vient pas seulement de la guerre. Beaucoup de peuples savent faire la guerre. Rome se distingue par sa capacité à intégrer. Après une victoire, elle peut détruire, mais elle peut aussi accorder des droits, créer des alliances, intégrer des élites locales, construire des colonies. Les vaincus ne deviennent pas toujours de simples ennemis permanents : certains finissent par participer au système romain.\n\nCette capacité donne à Rome un réservoir humain énorme. Lorsqu’elle perd des batailles, elle peut reconstituer des armées. Lorsqu’elle conquiert, elle transforme la conquête en réseau durable.`},
{t:'La République : une machine politique instable mais efficace',body:`Avant les empereurs, Rome est une République. Le pouvoir est partagé entre plusieurs institutions : magistrats, Sénat, assemblées. Les grandes familles aristocratiques dominent largement, mais la plèbe obtient progressivement des droits. Ce n’est pas une démocratie moderne, mais ce n’est pas non plus une monarchie simple.\n\nLa République romaine fonctionne beaucoup par compétition. Les élites cherchent la gloire, les commandements militaires, les honneurs. Cette compétition pousse à l’expansion : gagner une guerre, c’est obtenir du prestige, du butin, des terres, des clients.\n\nMais le succès crée ses propres problèmes. Les conquêtes enrichissent certains, ruinent parfois de petits paysans, multiplient les esclaves, donnent à certains généraux des armées fidèles à leur personne. Rome devient trop grande pour ses anciennes règles. Les tensions sociales et politiques s’aggravent.`},
{t:'De César à Auguste : la République bascule',body:`Jules César n’apparaît pas dans un système paisible. Il arrive dans une République déjà secouée par les rivalités, les guerres civiles et les ambitions personnelles. Ses conquêtes en Gaule lui donnent une gloire immense et une armée fidèle. Quand le conflit avec ses adversaires devient irréconciliable, il franchit le Rubicon : c’est le symbole d’un chef militaire qui amène ses légions dans la politique intérieure.\n\nCésar devient dictateur, puis il est assassiné. Ses meurtriers veulent sauver la République, mais le résultat est une nouvelle guerre civile. Finalement, Octave, son héritier politique, devient Auguste. Il conserve des apparences républicaines, mais concentre le pouvoir.\n\nL’Empire naît donc moins d’un coup de théâtre que d’une crise longue : Rome a conquis un monde immense, mais ses institutions n’arrivent plus à l’encadrer.`}
],
quiz:[['Rome commence comme…',['une petite cité italienne','un empire mondial immédiat','une colonie chinoise','une ville égyptienne'],0],['Une force majeure de Rome est…',['sa capacité à intégrer des vaincus','son refus de toute alliance','son absence d’armée','son isolement complet'],0],['Avant l’Empire, Rome est principalement…',['une République','un royaume médiéval','une théocratie moderne','une démocratie contemporaine'],0],['Pourquoi les conquêtes fragilisent-elles la République ?',['Elles enrichissent certains généraux et aggravent les tensions','Elles suppriment toute rivalité','Elles font disparaître les armées','Elles interdisent la politique'],0],['Que symbolise le Rubicon ?',['L’entrée de César et de ses légions dans la crise politique','La naissance de l’Égypte','Une fête religieuse grecque','La chute de Constantinople'],0],['Auguste fait quoi ?',['Il concentre le pouvoir tout en gardant des formes républicaines','Il abolit Rome','Il devient pharaon','Il fonde Athènes'],0],['La République était-elle une démocratie moderne ?',['Non','Oui exactement'],0],['L’Empire naît surtout…',['d’une longue crise des institutions républicaines','d’une élection moderne paisible','d’une invasion viking','d’une révolution industrielle'],0]]}
];
const state=JSON.parse(localStorage.getItem('histoState')||'{"done":{},"xp":0,"streak":0,"last":""}');
function save(){localStorage.setItem('histoState',JSON.stringify(state))}
function today(){return new Date().toISOString().slice(0,10)}
function complete(id,xp){if(!state.done[id]){state.done[id]=true;state.xp+=xp;if(state.last!==today()){state.streak+=1;state.last=today()}save()}}
let view='home', current=null, page=0, qi=0, score=0, answered=false;
function el(s){return document.querySelector(s)}
function render(){const app=el('#app'); app.innerHTML=top()+`<main class="wrap">${screens[view]()}</main>`+nav(); document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{view=b.dataset.go;render()});}
function top(){return `<div class="top"><div class="topin"><div class="brand">HistoDaily</div><div class="pill">⭐ ${state.xp} XP · 🔥 ${state.streak}</div></div></div>`}
function nav(){return `<div class="bottom"><div class="nav"><button data-go="home" class="${view==='home'?'active':''}">🏠<br>Accueil</button><button data-go="path" class="${view==='path'?'active':''}">📚<br>Parcours</button><button data-go="review" class="${view==='review'?'active':''}">🧠<br>Réviser</button><button data-go="profile" class="${view==='profile'?'active':''}">👤<br>Profil</button></div></div>`}
const screens={home(){let next=lessons.find(l=>!state.done[l.id])||lessons[0];return `<section class="card hero"><h1>5 à 10 minutes d’histoire par jour.</h1><p>Lis une vraie leçon, réponds à un quiz plus solide, gagne de l’XP et avance dans le parcours.</p><button class="btn big" onclick="start('${next.id}')">Continuer : ${next.title}</button></section><section class="stat"><div><b>${Object.keys(state.done).length}/${lessons.length}</b><span class="muted">leçons</span></div><div><b>${state.xp}</b><span class="muted">XP</span></div><div><b>${state.streak}</b><span class="muted">série</span></div></section>`},
path(){return `<h2>Parcours chronologique</h2><div class="grid">${lessons.map((l,i)=>`<button class="lesson" onclick="start('${l.id}')"><span class="badge">${l.icon}</span><span><b>${state.done[l.id]?'✅ ':''}${l.title}</b><small>${l.era} · ${l.minutes} min · ${l.quiz.length} questions</small></span></button>`).join('')}</div>`},
lesson(){const l=current,p=l.pages[page];return `<section class="card text"><div class="kicker">${l.era} · page ${page+1}/${l.pages.length}</div><h2>${p.t}</h2>${p.body.split('\n\n').map(x=>`<p>${x}</p>`).join('')}<div class="note">À la fin, tu auras ${l.quiz.length} questions. Le but n’est pas de tout retenir au mot près, mais de comprendre la logique historique.</div><div class="row">${page>0?`<button class="btn secondary" onclick="page--;render()">← Précédent</button>`:''}${page<l.pages.length-1?`<button class="btn" onclick="page++;render()">Suite →</button>`:`<button class="btn" onclick="startQuiz()">Commencer le quiz</button>`}</div></section>`},
quiz(){const l=current,q=l.quiz[qi];return `<section class="card"><div class="kicker">Question ${qi+1}/${l.quiz.length}</div><h2>${q[0]}</h2><div>${q[1].map((o,i)=>`<button class="quizOpt" onclick="answer(${i})">${o}</button>`).join('')}</div><div id="feedback"></div></section>`},
result(){const l=current;return `<section class="card hero"><h1>${score}/${l.quiz.length}</h1><p>${score>=Math.ceil(l.quiz.length*.7)?'Leçon validée. Tu as compris l’essentiel.':'Pas grave : relis la leçon et retente le quiz.'}</p>${score>=Math.ceil(l.quiz.length*.7)?`<button class="btn big" onclick="finishLesson()">Valider +${l.xp} XP</button>`:`<button class="btn big" onclick="page=0;view='lesson';render()">Relire</button>`}</section>`},
review(){const done=lessons.filter(l=>state.done[l.id]);return `<section class="card"><h2>Révisions</h2><p class="muted">Pour l’instant, les révisions reprennent les leçons terminées. La prochaine étape sera de faire revenir uniquement les questions ratées.</p>${done.length?done.map(l=>`<button class="lesson" onclick="start('${l.id}')"><span class="badge">${l.icon}</span><span><b>${l.title}</b><small>Relire et refaire le quiz</small></span></button>`).join(''):'<p>Aucune leçon terminée pour le moment.</p>'}</section>`},
profile(){const pct=Math.round(Object.keys(state.done).length/lessons.length*100);return `<section class="card"><h2>Profil</h2><div class="stat"><div><b>${state.xp}</b><span class="muted">XP</span></div><div><b>${state.streak}</b><span class="muted">jours</span></div><div><b>${pct}%</b><span class="muted">parcours</span></div></div><div class="sep"></div><div class="progress"><div class="bar" style="width:${pct}%"></div></div><button class="btn ghost big" onclick="resetAll()">Réinitialiser</button></section>`}}
function start(id){current=lessons.find(l=>l.id===id);page=0;view='lesson';render()}
function startQuiz(){qi=0;score=0;answered=false;view='quiz';render()}
function answer(i){if(answered)return;answered=true;const q=current.quiz[qi];const opts=document.querySelectorAll('.quizOpt');opts[i].classList.add(i===q[2]?'correct':'wrong');opts[q[2]].classList.add('correct');if(i===q[2])score++;el('#feedback').innerHTML=`<button class="btn big" onclick="nextQ()">${qi<current.quiz.length-1?'Question suivante':'Voir le résultat'}</button>`}
function nextQ(){qi++;answered=false;if(qi>=current.quiz.length){view='result'}render()}
function finishLesson(){complete(current.id,current.xp);view='path';render()}
function resetAll(){if(confirm('Tout remettre à zéro ?')){localStorage.removeItem('histoState');location.reload()}}
render();
