window.LESSONS = [
  {
    id:'prehistoire-01', era:'Préhistoire', title:'Avant l’histoire : survivre sans villes ni royaumes', xp:40,
    screens:[
      {title:'Le monde avant les États', text:`<p>La Préhistoire, ce n’est pas juste “des hommes avec des silex”. C’est l’immense période pendant laquelle les humains vivent sans écriture, sans État, sans monnaie, sans armée permanente, sans impôts et sans grandes villes.</p><p>Ça ne veut pas dire qu’ils sont “simples” ou “primitifs”. Ils savent observer les saisons, suivre les animaux, fabriquer des outils, transmettre des techniques, raconter des histoires, enterrer leurs morts et décorer des grottes. Leur monde est différent du nôtre, mais il demande énormément d’intelligence pratique.</p><p>Quand on parle de Préhistoire, on parle donc surtout d’une question : comment des groupes humains ont-ils réussi à vivre, se déplacer, coopérer et survivre pendant des dizaines de milliers d’années ?</p>`},
      {title:'Une durée difficile à imaginer', text:`<p>Notre histoire écrite est minuscule par rapport à l’histoire humaine. Les premières formes d’écriture apparaissent vers 3300 avant notre ère en Mésopotamie. Mais Homo sapiens existe depuis environ 300 000 ans.</p><p>Autrement dit, la presque totalité de l’histoire de notre espèce se déroule avant les livres, les rois, les lois écrites et les grandes batailles célèbres.</p><p class="quote">Image mentale : si toute l’histoire d’Homo sapiens tenait dans une journée, l’écriture n’arriverait que très tard dans la soirée.</p>`},
      {title:'Chasseurs-cueilleurs', text:`<p>Pendant très longtemps, les humains vivent principalement de chasse, de pêche, de cueillette et de collecte. Ils ne produisent pas encore leur nourriture : ils la trouvent dans leur environnement.</p><p>Ce mode de vie impose de connaître très finement le territoire. Il faut savoir quelles plantes sont comestibles, quand les animaux migrent, où trouver de l’eau, comment éviter le froid, comment conserver de la nourriture et comment fabriquer des outils adaptés.</p><p>Leur richesse n’est pas dans des coffres. Elle est dans la mémoire collective, les savoir-faire, les liens du groupe et la capacité à bouger.</p>`},
      {title:'Pas des brutes isolées', text:`<p>On imagine parfois l’homme préhistorique comme un individu brutal qui survit seul. C’est trompeur. Un humain isolé est fragile. Le groupe est une technologie en soi.</p><p>Coopérer permet de chasser plus efficacement, protéger les enfants, partager les informations, soigner les blessés, transmettre les gestes et organiser les déplacements.</p><p>La Préhistoire est donc aussi une histoire sociale : comment vivre ensemble avant les lois écrites ? comment décider ? comment partager ? comment éviter les conflits ? On n’a pas toutes les réponses, mais les traces archéologiques montrent des sociétés plus riches qu’un cliché de “cavernes et massues”.</p>`},
      {title:'Pourquoi c’est important', text:`<p>Comprendre la Préhistoire permet de comprendre le reste. L’agriculture, les villages, les chefs, les royaumes et les empires ne tombent pas du ciel. Ils apparaissent après une très longue période où les humains expérimentent d’autres manières de vivre.</p><p>Le grand basculement viendra avec le Néolithique : des humains commencent à cultiver des plantes, domestiquer des animaux, rester plus longtemps au même endroit et transformer leur environnement.</p><p>Mais avant de parler de ce changement, il faut retenir ceci : pendant l’immense majorité de notre histoire, les humains n’ont pas vécu dans des pays. Ils ont vécu dans des groupes mobiles, dépendants de la nature, mais capables d’une remarquable adaptation.</p>`}
    ],
    quiz:[
      {q:'Qu’est-ce qui marque généralement la fin de la Préhistoire ?', a:['L’apparition de l’écriture','La disparition des mammouths','La construction des pyramides','La naissance de Rome'], ok:0},
      {q:'Pendant la plus grande partie de leur histoire, les humains vivent surtout comme…', a:['chasseurs-cueilleurs','citoyens de grands empires','marchands urbains','soldats professionnels'], ok:0},
      {q:'Pourquoi le groupe est-il essentiel dans la Préhistoire ?', a:['Il permet la coopération et la transmission des savoirs','Il sert surtout à élire un roi','Il permet de payer des impôts','Il remplace l’écriture'], ok:0},
      {q:'L’écriture apparaît environ…', a:['vers 3300 avant notre ère','vers 30 000 avant notre ère','vers 753 avant notre ère','vers 1492'], ok:0},
      {q:'Homo sapiens existe depuis environ…', a:['300 000 ans','3 000 ans','30 millions d’années','10 000 ans seulement'], ok:0},
      {q:'Dans une société de chasseurs-cueilleurs, la richesse principale est plutôt…', a:['le savoir-faire et la connaissance du territoire','l’or stocké dans des palais','les impôts collectés','les usines'], ok:0},
      {q:'Le Néolithique correspond surtout au début…', a:['de l’agriculture et de la sédentarisation progressive','des cathédrales','de l’imprimerie','de la Révolution française'], ok:0},
      {q:'Dire que les humains préhistoriques sont “primitifs” est trompeur parce que…', a:['leurs techniques et leur organisation demandent beaucoup d’intelligence','ils avaient déjà Internet','ils vivaient tous dans des villes','ils écrivaient des livres complexes'], ok:0}
    ]
  },
  {
    id:'prehistoire-02', era:'Préhistoire', title:'Le Néolithique : quand l’humanité change de rythme', xp:50,
    screens:[
      {title:'La révolution lente', text:`<p>Le Néolithique est parfois appelé “révolution néolithique”. Le mot est utile, mais il peut tromper : ce changement ne se fait pas en une semaine ni partout en même temps.</p><p>Dans certaines régions, des groupes humains commencent à cultiver des céréales, à domestiquer des animaux et à s’installer plus durablement. Ce n’est pas une invention unique qui se répand comme une mode. C’est un ensemble de transformations lentes, avec des essais, des échecs et des adaptations locales.</p><p>Mais les conséquences sont énormes : produire sa nourriture change la relation au temps, au territoire, au travail et au pouvoir.</p>`},
      {title:'Pourquoi cultiver ?', text:`<p>La question paraît simple : pourquoi se fatiguer à cultiver si la chasse et la cueillette fonctionnaient ? Justement, il n’y a pas une seule réponse.</p><p>Dans certaines régions, le climat change après la dernière période glaciaire. Des plantes sauvages deviennent plus abondantes. Des groupes restent plus longtemps dans les mêmes zones. Peu à peu, ils apprennent à sélectionner les graines, protéger les pousses, récolter davantage.</p><p>L’agriculture n’est donc pas forcément un “progrès confortable” au départ. Elle demande du travail. Mais elle permet aussi de nourrir plus de monde sur un espace plus réduit.</p>`},
      {title:'Le village change tout', text:`<p>Quand on reste au même endroit, beaucoup de choses changent. On peut construire des maisons plus solides, accumuler des réserves, fabriquer des objets plus lourds, enterrer les morts près du lieu de vie, défendre un territoire.</p><p>Le village crée une nouvelle stabilité. Mais il crée aussi de nouveaux problèmes : maladies liées à la proximité, conflits autour des terres, dépendance aux récoltes, inégalités possibles dans le stockage des ressources.</p><p>Ce n’est donc pas simplement “mieux qu’avant”. C’est un autre monde, avec de nouvelles forces et de nouvelles fragilités.</p>`},
      {title:'Domestiquer le vivant', text:`<p>Domestiquer, ce n’est pas juste capturer un animal. C’est transformer progressivement une relation entre humains, plantes et animaux.</p><p>Les humains sélectionnent les plantes qui donnent les meilleurs grains, les animaux les moins agressifs, les espèces les plus utiles. Sur des générations, cela modifie le vivant.</p><p>Le blé cultivé, les chèvres, les moutons, les bovins ou les porcs deviennent des éléments centraux de sociétés nouvelles. L’humanité ne se contente plus de s’adapter à la nature : elle commence à la remodeler massivement.</p>`},
      {title:'La naissance des surplus', text:`<p>Un point capital du Néolithique est le surplus. Si une communauté produit plus de nourriture qu’elle n’en consomme immédiatement, elle peut stocker.</p><p>Le stockage permet de traverser les mauvaises saisons. Mais il pose une question explosive : qui garde les réserves ? qui décide de leur distribution ? qui protège les greniers ?</p><p>À long terme, les surplus ouvrent la porte à la spécialisation. Certaines personnes peuvent passer plus de temps à fabriquer des objets, organiser les rituels, gérer les échanges ou exercer une autorité. On commence à voir les bases lointaines des sociétés plus hiérarchisées.</p>`},
      {title:'À retenir', text:`<p>Le Néolithique n’est pas juste “l’invention de l’agriculture”. C’est un basculement complet : produire, stocker, s’installer, transmettre des terres, protéger des réserves, vivre plus nombreux.</p><p>Ce changement prépare beaucoup de choses : les villages, les inégalités, les échanges, les conflits territoriaux, puis plus tard les villes et les États.</p><p>On peut presque dire que l’histoire politique commence ici, très lentement, quand la nourriture devient une ressource produite, stockée et disputée.</p>`}
    ],
    quiz:[
      {q:'Le Néolithique est surtout associé à…', a:['l’agriculture, la domestication et la sédentarisation','l’apparition des chevaliers','la découverte de l’Amérique','la chute de Rome'], ok:0},
      {q:'Pourquoi le terme “révolution néolithique” peut-il être trompeur ?', a:['car le changement est lent et inégal selon les régions','car il n’y a aucun changement important','car il désigne une guerre précise','car il commence au XIXe siècle'], ok:0},
      {q:'Un surplus agricole permet notamment…', a:['le stockage et la spécialisation des activités','de supprimer tous les conflits','de rendre l’écriture inutile','de revenir automatiquement au nomadisme'], ok:0},
      {q:'La sédentarisation favorise…', a:['la construction d’habitats plus durables','la disparition des villages','l’absence de réserves','l’impossibilité d’échanger'], ok:0},
      {q:'Domestiquer une plante ou un animal signifie…', a:['modifier progressivement une relation et sélectionner certains traits','simplement le regarder vivre','l’interdire dans les villages','l’écrire sur une tablette'], ok:0},
      {q:'L’agriculture au départ est…', a:['un changement utile mais exigeant, pas forcément confortable','un loisir sans effort','une invention romaine','une technique apparue après l’imprimerie'], ok:0},
      {q:'Quel problème nouveau peut venir avec les réserves ?', a:['savoir qui les contrôle et les distribue','ne plus avoir besoin de nourriture','l’impossibilité de vivre en groupe','la disparition des maisons'], ok:0},
      {q:'À long terme, le Néolithique prépare…', a:['les villages, les hiérarchies et plus tard les États','la fin définitive de toute organisation','la disparition des techniques','l’abandon de tous les territoires'], ok:0}
    ]
  }
];
