const { mysteries } = require('./_data');
module.exports = (req, res) => res.status(200).json({
  ok: true,
  app: "HistoDaily",
  version: "1.0.0-beta.54",
  target: "vercel",
  content: {
    mysteries: mysteries.length,
    archiveDaysVisible: 7,
    archiveUnlockCost: 2,
    dailyRewardGems: 1,
    premiumCourses: 192,
    pseudoLocal: true,
    scoreBreakdown: true,
    spoilerFreeShare: true,
    installPrompt: true,
    localBackupExport: true,
    friendCodeLocal: true,
    performanceMode: true,
    qualityDiagnostic: true,
    downloadableBackup: true,
    learnFilters: true,
    learnSearch: true,
    sessionCoach: true,
    normalizedQuizExplanations: true,
    keyFactsEveryCourse: true,
    contentWeakPointPass: true,
    premiumKeyFactsRendered: true,
    thirtySecondTakeaways: false,
    lessonMemoCards: false,
    beta44FoundationsContentPass: true,
    beta46NavigationMemoPass: true,
    beta47InputFocusFix: true,
    beta47LessonTabs: true,
    beta49DebugHomeCleanup: true,
    beta49CourseValidateFix: true,
    beta49ExpressStrengthened: true,
    beta50IndependentDailyCourse: true,
    beta50NoTraceTrapExpress: true,
    beta50MysteryLinkedCourseAfterSolveOnly: true,
    beta51ContentSanitizer: true,
    beta51DebugAudit: true,
    beta51LockedSpoilerCourse: true,
    beta51MultiplayerFoundationOnly: true,
    beta52FriendsProfilesLeaderboards: true,
    friendProfilesLocal: true,
    noChatByDesign: true,
    serverMultiplayerReady: Boolean(process.env.SUPABASE_URL && process.env.SUPABASE_SERVICE_ROLE_KEY),
    beta54InviteLinks: true,
    beta54ScoreSubmitApi: true,
    beta54SupabaseOptional: true,
    beta54NoChatStill: true
  }
});
