-- HistoDaily beta54 — schéma Supabase minimal
-- À exécuter dans Supabase SQL Editor quand tu voudras activer le vrai multi.

create table if not exists public.hd_profiles (
  player_id text primary key,
  pseudo text not null,
  friend_code text,
  level integer default 1,
  xp integer default 0,
  solved_count integer default 0,
  streak integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.hd_scores (
  id bigint generated by default as identity primary key,
  player_id text not null references public.hd_profiles(player_id) on delete cascade,
  pseudo text not null,
  friend_code text,
  mystery_id text not null,
  period_key text not null,
  scope text not null default 'daily',
  score integer not null default 0,
  hints integer not null default 0,
  tries integer not null default 1,
  difficulty text,
  level integer default 1,
  xp integer default 0,
  solved_count integer default 0,
  streak integer default 0,
  solved_at timestamptz default now(),
  created_at timestamptz default now()
);

create index if not exists hd_scores_period_scope_score_idx
on public.hd_scores(period_key, scope, score desc);

create table if not exists public.hd_friends (
  id bigint generated by default as identity primary key,
  player_id text not null,
  friend_player_id text,
  friend_code text not null,
  friend_pseudo text,
  created_at timestamptz default now(),
  unique(player_id, friend_code)
);
